
//* TRANSLATE PAGE ----------> 
const lang = {
    en: {
        loading: "Loading...",
        tit: "The camera",
        desc: "Let's steal a moment from life",
        home: "Home",
        gallary: "Gallary",
        cameras: "Cameras",
        testmonials: "Testmonials",
        translate: "Langauge",
        langBtn: "العربية",
        whatCanDoTitle: "What Can camera does?",
        btnHero: "Call now",
        capturePhotos: "Capture Photos",
        takeStillImage: "Take still images",
        recordVideos: "Record Videos",
        captureImage: "Capture moving images with sound",
        zoomInOut: "Zoom In/Out",
        adjustLens: "Adjust the lens to focus on distant or close subjects",
        adjustFocus: "Adjust Focus",
        automaticManual: "Automatically or manually focus on subjects",
        changeExposure: "Change Exposure",
        adjustAmount: "Adjust the amount of light entering the camera",
        changeISO: "Change ISO Settings",
        controlCamera: "Control the camera’s sensitivity to light",
        applyFilters: "Apply Filters",
        addartistic: "Add artistic effects to photos and videos",
        shootBurstMode: "Shoot in Burst Mode",
        captureSeveralPhotos: "Capture several photos in quick succession",
        captureSeveralPhotos: "",
        gallaryHead: "gallary",
        cameraKind: "Kind of cameras",
        testmoials: "testmoials",
        contacts: "Contact us",
        all: "All",
        canon: "Canon",
        nikon: "Nikon",
        sony: "Sony",
        descCamera: "Canon Inc. is a Japanese multinational corporation known for its imaging and optical products, including cameras, camcorders, printers, and medical",
        descCamList1: "Headquarters: Ota, Tokyo, Japan",
        descCamList2: "Development: Initially focused on manufacturing 35mm cameras, Canon expanded",
        closeBtn: "Close",
        showDetails: "Show details",
        testmonialsParagraphX: "Lorem ipsum dolor sit amet consectetur adipisicing elit. A beatae iure assumenda non itaque labore repellat recusandae consequuntur et voluptatem quo, provident dignissimos placeat odio accusantium aut aliquam! Deleniti, quia.",
        clientName: "Client name",
        username: "Username",
        email: "Email",
        subject: "Subject",
        message: "Message",
        addressTitle: "Address",
        callUs: "Call us",
        emailUs: "Email us",
        address: "A108 Adam Street, New York, NY 535022",
        submit: "Send message",

    },
    ar: {
        loading: "جاري التحميل...",
        tit: "الكاميرا",
        desc: "هيا لنسرق من الحياة لحظة",
        home: "الرئيسية",
        gallary: "معرض الصور",
        cameras: "الكاميرات",
        testmonials: "أراء العملاء",
        contacts: "تواصل معنا",
        translate: "اللغة",
        langBtn: "English",
        whatCanDoTitle: "ماذا تستطيع أن تفعل الكاميرا؟",
        btnHero: "إتصل الآن",
        capturePhotos: "إلتقاط الصور",
        takeStillImage: "إلتقاط الصور الثابتة",
        recordVideos: "تسجيل فيدوهات",
        captureImage: "التقاط الصور المتحركة بالصوت",
        zoomInOut: "تكبير وتصغير",
        adjustLens: "اضبط العدسة للتركيز على الأهداف البعيدة أو القريبة",
        adjustFocus: "ضبط التركيز",
        automaticManual: "التركيز تلقائيًا أو يدويًا على الموضوعات",
        changeExposure: "تغيير التعرض",
        adjustAmount: "ضبط كمية الضوء الداخلة إلى الكاميرا",
        changeISO: "تغيير إعدادات ISO",
        controlCamera: "التحكم في حساسية الكاميرا للضوء",
        addartistic: "إضافة تأثيرات فنية على الصور ومقاطع الفيديو",
        shootBurstMode: "تبادل لاطلاق النار في وضع الاندفاع",
        applyFilters: "تطبيق التأثيرات المخلفتة",
        captureSeveralPhotos: "التقاط عدة صور في تتابع سريع",
        gallaryHead: "معرض الصور",
        cameraKind: "أنواع الكاميرات",
        testmoials: "أراء عملائنا",
        all: "الجميع",
        canon: "كانون",
        nikon: "نيكون",
        sony: "سوني",
        descCamera: "شركة كانون هي شركة يابانية متعددة الجنسيات معروفة بصناعتها للتصوير والتصوير  المنتجات البصرية، بما في ذلك الكاميرات وكاميرات الفيديو والطابعات والطبية",
        descCamList1: "المقر الرئيسي: أوتا، طوكيو، اليابان",
        descCamList2: "التطوير: ركزت شركة كانون في البداية على تصنيع كاميرات 35 ملم موسع",
        closeBtn: "إغلاق",
        showDetails: "التفاصيل",
        testmonialsParagraphX: "لقد اشتريت مؤخرًا جهاز القهوة الجديد، وأنا معجب جدًا به. يتميز الجهاز بتصميم أنيق وعصري يضفي جمالية على مطبخي. بالإضافة إلى ذلك، فإن الأداء الممتاز للجهاز يجعل تحضير القهوة أمرًا سريعًا وسهلًا، مع نكهة غنية ومثالية في كل مرة. بالتأكيد، أصبح هذا الجهاز جزءًا لا غنى عنه في روتيني اليومي.",
        clientName: "اسم العميل",
        username: "الاسم",
        email: "البريد الإلكتروني",
        subject: "الموضوع",
        message: "الرسالة",
        addressTitle: "العنوان",
        callUs: "اتصل بنا",
        emailUs: "راسلنا",
        address: "A108 شارع آدم، نيويورك، نيويورك 535022",
        submit: "إرسال الرسالة"

    }
}